# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 3
name = "Another JavaScript Compute App"
service_id = "lMHWg3XbW0Vr7o0fum0Po3"

[local_server]

  [local_server.backends]

    [local_server.backends.website]
      override_host = "suesmith.github.io"
      url = "https://suesmith.github.io/"

[scripts]
  build = "npm run build"
  post_init = "npm install"

[setup]

  [setup.backends]

    [setup.backends.website]
      address = "suesmith.github.io"
