name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install project dependencies
      run: npm install

    - name: Deploy to the Compute platform
      uses: fastly/compute-actions@v5
      with:
        project_directory: './compute-js'
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
